---
- name: Install epel-release
  yum:
    name: epel-release
- name: Install remi-release
  yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present
- name: Add remi-php72
  yum_repository:
    name: remi-php72
    description: Remi's PHP 7.2 RPM repository for Enterprise Linux $releasever - $basearch
    mirrorlist: http://rpms.remirepo.net/enterprise/$releasever/php72/mirror
    enabled: yes
    gpgcheck: 1
    gpgkey: http://rpms.remirepo.net/RPM-GPG-KEY-remi
- name: Install requirement packeges
  yum:
    name:
     - php-fpm
     - php-cli
     - php-gd
     - php-json
     - php-mcrypt
     - php-xml
     - php-curl
     - php-pgsql
     - nginx
     - wget
     - unzip
     - git
- name: Disable SELinux
  selinux:
    state: disabled
- name: Copy nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
- name: Copy wordpress.conf
  template:
    src: wordpress.conf.j2
    dest: /etc/nginx/conf.d/wordpress.conf
- name: Set user and group to php-fpm
  lineinfile:
    path: /etc/php-fpm.d/www.conf
    regexp: "^{{ item.var }}"
    line: "{{ item.value }}"
  loop:
    - { var: "user = apache", value: "user = nginx" }
    - { var: "group = apache", value: "group = nginx" }
- name: Set cgi.fix_pathinfo 0
  lineinfile:
    path: /etc/php.ini
    regexp: "^cgi.fix_pathinfo=1"
    line: cgi.fix_pathinfo=0
- name: Download wordpress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: "{{ root_directory }}/latest.tar.gz"
- name: Extract wordpress archive
  unarchive:
    src: "{{ root_directory }}/latest.tar.gz"
    dest: "{{ root_directory }}"
    remote_src: yes
    extra_opts:
    - --strip-components=1
    owner: nginx
    group: nginx
- name: Download pg4wp
  git:
    repo: 'https://github.com/kevinoid/postgresql-for-wordpress.git'
    dest: "{{ root_directory }}/postgresql-for-wordpress"
- name: Copy pg4wp folder to wp-content
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: yes
    owner: nginx
    group: nginx
  loop:
    - { src: "{{ root_directory }}/postgresql-for-wordpress/pg4wp", dest: "{{ root_directory }}/wp-content"}
    - { src: "{{ root_directory }}/wp-content/pg4wp/db.php", dest: "{{ root_directory }}/wp-content/db.php"}
- name: Remove postgresql-for-wordpress directory
  file:
    path: "{{ root_directory }}/wp-content/postgresql-for-wordpress"
    state: absent
- name: Copy wp-config.php template
  template:
    src: wp-config.php.j2
    dest: "{{ root_directory }}/wp-config.php"

  notify: 
    - restart nginx
    - restart php-fpm

  