---
- name: Install wget unzip git
  yum:
    name:
     - wget
     - unzip
     - git
- name: Disable SELinux
  selinux:
    state: disabled
- name: Download wordpress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: "{{ root_directory }}/latest.tar.gz"
- name: Extract wordpress archive
  unarchive:
    src: "{{ root_directory }}/latest.tar.gz"
    dest: "{{ root_directory }}"
    remote_src: yes
    extra_opts:
    - --strip-components=1
    owner: nginx
    group: nginx
- name: Download pg4wp
  git:
    repo: 'https://github.com/kevinoid/postgresql-for-wordpress.git'
    dest: "{{ root_directory }}/postgresql-for-wordpress"
- name: Copy pg4wp folder to wp-content
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: yes
    owner: nginx
    group: nginx
  loop:
    - { src: "{{ root_directory }}/postgresql-for-wordpress/pg4wp", dest: "{{ root_directory }}/wp-content"}
    - { src: "{{ root_directory }}/wp-content/pg4wp/db.php", dest: "{{ root_directory }}/wp-content/db.php"}
- name: Remove postgresql-for-wordpress directory
  file:
    path: "{{ root_directory }}/postgresql-for-wordpress"
    state: absent
- name: Copy wp-config.php template
  template:
    src: wp-config.php.j2
    dest: "{{ root_directory }}/wp-config.php"

  