---
- import_tasks: install_postgresql.yaml
  when: inventory_hostname == "{{ postgresql_host }}"
  tags: postgresql
- import_tasks: install_wordpress.yaml
  when: inventory_hostname == "{{ wordpress_host }}"
  tags: wordpress